Compile expressions but do not emit the assembly.
UiPath/corewf pull request #286
Opened 2023-11-07 12:24 UTC by aoltean16

2023-12-19 12:25 UTC, mirceaarhip requested changes

2023-12-19 12:25 UTC, mirceaarhip commented on src/Perf/CoreWf.Benchmarks/ExpressionTextboxPerformance.cs
> +//    public class ExpressionTextboxPerformance
why is this code commented ?

2023-12-19 12:25 UTC, mirceaarhip commented on src/UiPath.Workflow/Activities/DesignerHelperImpl.cs
> +        var diagnostics = Task.Run(async () => await compilation.WithAnalyzers(_usedTypesAnalizerList).GetAllDiagnosticsAsync()).Result;
blazor is mono thread so .Result might block our precious thread

2023-12-19 12:25 UTC, mirceaarhip commented on src/UiPath.Workflow/Activities/DesignerHelperImpl.cs
> +        var compilation = Compiler.Compile(expressionText, isLocation, targetType ?? typeof(object), namespaces.ToList(), referencedAssemblies.ToList(), environment);
previous code ensures namespace/ referenced assembly are not null

2023-12-19 12:25 UTC, mirceaarhip commented on src/UiPath.Workflow/Activities/DesignerHelperImpl.cs
> -                var conditional = (ConditionalExpression) expression;
nit: i would recommend to split formatting changes to another PR , every reviewer will appreciate

2023-12-19 12:25 UTC, mirceaarhip commented on src/UiPath.Workflow/Activities/DesignerHelperImpl.cs
> +            var diagMessages = diagnostic.GetMessage()[1..^1].Split('|');
let's make sure that all this string manipulations are covered by tests and the cannot failed with null reference

2023-12-19 12:25 UTC, mirceaarhip commented on src/UiPath.Workflow/Activities/ScriptingJitCompiler.cs
> -    protected abstract CompilerHelper CompilerHelper { get; }
this is a breaking change; sw actually uses this member

2023-12-19 12:25 UTC, mirceaarhip commented on src/UiPath.Workflow/Activities/Utils/CompilerHelper.cs
> +    internal abstract class CompilerHelper
breaking change

2023-12-19 12:25 UTC, mirceaarhip commented on src/UiPath.Workflow/Microsoft/CSharp/Activities/CSharpDesignerHelper.cs
> -    public override JitCompilerHelper CreateJitCompilerHelper(string expressionText, HashSet<AssemblyName> references,
i think this allows injection of a compiler something which sw does (not sure if it good or not) but with this changes we won't be able to to this

2023-12-19 13:55 UTC, aoltean16 commented on src/UiPath.Workflow/Activities/DesignerHelperImpl.cs
> +            var diagMessages = diagnostic.GetMessage()[1..^1].Split('|');
They are covered indirectly in tests, but I've added 2 more just for sanity, that directly checks import references, and will make it fail if any string manipulation fails (tho, we own that diagnostic so unless we change it, it wont fail).

2023-12-20 09:51 UTC, marius-bughiu commented on src/UiPath.Workflow/Roslyn/UsedTypesAnalyzer.cs
> +        context.EnableConcurrentExecution();
We might need to add a check here for SW, similar to the one found in the compiler helpers for the `concurrentBuild` - I mean, I assume this is what this check does? 
 `!RuntimeInformation.IsOSPlatform(OSPlatform.Create("BROWSER"))`

2023-12-20 09:51 UTC, marius-bughiu commented on src/UiPath.Workflow/Roslyn/UsedTypesAnalyzer.cs
> +        public CSharpReferenceCounter(SyntaxTree syntaxTree, SemanticModel semanticModel, HashSet<string> usedTypes, CancellationToken cancellationToken)
It is a bit weird to pass the `cancellationToken` in the constructor as it effectively renders the instance single-use. We should move it as a parameter to the methods.

2023-12-20 09:51 UTC, marius-bughiu commented on src/UiPath.Workflow/Roslyn/UsedTypesAnalyzer.cs
> +    private sealed class CSharpReferenceCounter : CSharpSyntaxWalker, ITypeIdentifier
nit: the class name is a tiny bit confusing, since we don't really count references, we find used types. Maybe something along the lines `CSharpTypeIdentifier` would be more appropriate - would match the interface name as well (`ITypeIdentifier`).

2023-12-20 09:51 UTC, marius-bughiu commented on src/UiPath.Workflow/Activities/Utils/CSharpCompilerHelper.cs
> +        public override ParseOptions ScriptParseOptions { get; } = new CSharpParseOptions(kind: SourceCodeKind.Script);
You could in theory get rid of all the `as CSharpParseOptions` and `as CSharpCompilerHelper`, etc. by specifying the actual type in the override, like in this example you could do:

```
public override CSharpParseOptions ScriptParseOptions { get; } = new CSharpParseOptions(kind: SourceCodeKind.Script);
```

2023-12-20 09:51 UTC, marius-bughiu commented on src/UiPath.Workflow/Activities/Utils/CSharpCompilerHelper.cs
> +        private static object GetTypeNameFormatter()
nit: Move private method below the public ones.

2023-12-20 09:51 UTC, marius-bughiu commented on src/UiPath.Workflow/Roslyn/UsedTypesAnalyzer.cs
> +        return context.Compilation.Language == "C#"
nit: `CSharpHelper.Language` instead of `"C#"`?

2023-12-20 09:51 UTC, marius-bughiu commented on src/UiPath.Workflow/Activities/ExpressionCompiler.cs
> +        private static string GetTypeName(ITypeSymbol typeSymbol, Assembly assembly)
The `assembly` parameter is passed around but is not used for anything.

2024-01-02 16:22 UTC, aoltean16 commented on src/UiPath.Workflow/Activities/Utils/CSharpCompilerHelper.cs
> +        public override ParseOptions ScriptParseOptions { get; } = new CSharpParseOptions(kind: SourceCodeKind.Script);
since when is this a thing? damn life changer!

2024-01-02 16:33 UTC, aoltean16 commented on src/UiPath.Workflow/Roslyn/UsedTypesAnalyzer.cs
> +        context.EnableConcurrentExecution();
it adds unnecessary overhead for us and I dont think this is really a problem for them.

2024-01-02 16:36 UTC, aoltean16 commented on src/UiPath.Workflow/Roslyn/UsedTypesAnalyzer.cs
> +        public CSharpReferenceCounter(SyntaxTree syntaxTree, SemanticModel semanticModel, HashSet<string> usedTypes, CancellationToken cancellationToken)
removed it from Visit method altogether, as the whole operation is under 1ms, the overhead of checking is not worth it anyway.

2024-01-10 09:54 UTC, marius-bughiu approved these changes

2024-01-15 11:39 UTC, mirceaarhip approved these changes

2024-01-15 16:06 UTC, merged